spring:

  artemis:
    host: localhost
    port: 61616
    user: veladii
    password: password

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: springboot2.order
      routing-key: order

  jms:
    template:
      default-destination: springboot2.order.queue